package main

import (
	"bytes"
	"compress/gzip"
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

func compressBytes(data []byte) ([]byte, error) {
	var buf bytes.Buffer
	zw, err := gzip.NewWriterLevel(&buf, gzip.BestCompression)
	if err != nil {
		return nil, err
	}
	if _, err := zw.Write(data); err != nil {
		return nil, err
	}
	if err := zw.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func compressFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	compressed, err := compressBytes(data)
	if err != nil {
		return err
	}
	if err := os.WriteFile(dst, compressed, 0644); err != nil {
		return err
	}
	fmt.Printf("[+] Compressed %s: %d -> %d bytes (%.2f MB)\n", filepath.Base(src), len(data), len(compressed), float64(len(compressed))/1024/1024)
	return nil
}

func main() {
	assetsDir := "assets"
	if err := os.MkdirAll(assetsDir, 0755); err != nil {
		panic(err)
	}

	// 1. Pack model.onnx with compression + AES-256-GCM
	modelPath := "model.onnx"
	fmt.Printf("[*] Reading %s...\n", modelPath)
	rawModel, err := os.ReadFile(modelPath)
	if err != nil {
		panic(err)
	}

	fmt.Printf("[*] Compressing model (%d bytes)...\n", len(rawModel))
	compressedModel, err := compressBytes(rawModel)
	if err != nil {
		panic(err)
	}

	// Generate 32-byte AES key and 12-byte nonce
	key := make([]byte, 32)
	if _, err := io.ReadFull(rand.Reader, key); err != nil {
		panic(err)
	}

	block, err := aes.NewCipher(key)
	if err != nil {
		panic(err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		panic(err)
	}

	nonce := make([]byte, gcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		panic(err)
	}

	ciphertext := gcm.Seal(nonce, nonce, compressedModel, nil)
	encPath := filepath.Join(assetsDir, "model.enc")
	if err := os.WriteFile(encPath, ciphertext, 0644); err != nil {
		panic(err)
	}
	fmt.Printf("[+] Encrypted model written to %s: %d bytes (%.2f MB)\n", encPath, len(ciphertext), float64(len(ciphertext))/1024/1024)

	// Obfuscate key with XOR mask
	mask := make([]byte, 32)
	if _, err := io.ReadFull(rand.Reader, mask); err != nil {
		panic(err)
	}
	maskedKey := make([]byte, 32)
	for i := 0; i < 32; i++ {
		maskedKey[i] = key[i] ^ mask[i]
	}

	// Generate key_gen.go in current dir
	keyGenContent := fmt.Sprintf(`// Code generated by packer/pack.go; DO NOT EDIT.
package main

var (
	modelKeyMask = %#v
	modelKeyData = %#v
)

func getModelKey() []byte {
	k := make([]byte, 32)
	for i := 0; i < 32; i++ {
		k[i] = modelKeyData[i] ^ modelKeyMask[i]
	}
	return k
}
`, mask, maskedKey)

	if err := os.WriteFile("key_gen.go", []byte(keyGenContent), 0644); err != nil {
		panic(err)
	}
	fmt.Println("[+] Generated key_gen.go with XOR-obfuscated key")

	// 2. Compress dynamic libraries
	if _, err := os.Stat("libonnxruntime.dylib"); err == nil {
		compressFile("libonnxruntime.dylib", filepath.Join(assetsDir, "libonnxruntime.dylib.gz"))
	}
	if _, err := os.Stat("onnxruntime.dll"); err == nil {
		compressFile("onnxruntime.dll", filepath.Join(assetsDir, "onnxruntime.dll.gz"))
	}

	fmt.Println("[✔] Assets packing complete!")
}
